# Taken on 2025-08-30 from: https://github.com/gradle/actions/blob/main/docs/dependency-submission.md#general-usage
name: 'Dependency Submission & Review'

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write

jobs:
  dependency-submission-and-review:
    
    # 2026-05-15 - DISABLE WORKFLOW: This workflow consistently fails because the IntelliJ Platform currently brings in two
    #                                bad versions of `com.fasterxml.jackson.core:jackson-core` and one bad version of 
    #                                `io.undertow:undertow-core`, which causes the workflow to fail and give a bad signal 
    #                                during CI. I suspect that these dependencies need to be bumped in either (a) IntelliJ
    #                                platform, (b) the IntelliJ Gradle plugin, (c) both.
    if: false
    
    runs-on: ubuntu-latest
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        timeout-minutes: 1

      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        timeout-minutes: 5
        with:
          distribution: zulu
          java-version: 21

      # Generate and submit dependency graph
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          # Reducing storage costs for saved dependency graph artifacts (store for 1 day instead of 30 days)
          # See: https://github.com/gradle/actions/blob/main/docs/dependency-submission.md#reducing-storage-costs-for-saved-dependency-graph-artifacts
          artifact-retention-days: 1 # Default is 30 days or as configured for repository

          # Publishing a Develocity Build Scan® from your dependency submission workflow
          # Why: A Build Scan makes it easy to determine the source of any dependency vulnerabilities in your project.
          # See: https://github.com/gradle/actions/blob/main/docs/dependency-submission.md#publishing-a-develocity-build-scan-from-your-dependency-submission-workflow
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"

      # Dependency Review (on PR only)
      - name: Dependency Review
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
